### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by DB1973** [Gobidev/voicemeeter-auto-affinity#1]
I downloaded v2 and after install and reboot it does not show affinity set to 1 cpu it has all selected still. Not sure if its my machine or the bat file. Installed as admi as well.

**Comment by Gobidev** [comment]
Ok, can you check the following things:
- When you run the install.bat file, does it report any errors?
- Check if the file %localappdata%\set-audiodg-affinity.vbs exists, you can open the folder by pressing WIN + R and entering `%localappdata%`
- Open Task Scheduler (by pressing WIN + R and typing `taskschd.msc`) scroll through the tasks at the bottom and check if a task with the name "audiodg-affinity" exists

**Comment by DB1973** [comment]
No errors when installing. I do have the set-audiodg-affinity.vbs. Also the active tasks show audiodg-affinity.

**Comment by Gobidev** [comment]
Ok, can you open a command prompt as administrator and enter
```bat
%localappdata%\set-audiodg-affinity.vbs
```
and check if it throws any error. If not, check if that sets the affinity of audiodg.exe to one core

**Comment by DB1973** [comment]
Came back with this error

%localappdata%\set-audiodg-affinity.vbs : The module '%localappdata%' could not be loaded. For more information, run
'Import-Module %localappdata%'.
At line:1 char:1
+ %localappdata%\set-audiodg-affinity.vbs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (%localappdata%\set-audiodg-affinity.vbs:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

**Comment by Gobidev** [comment]
Ok, it looks like you don't have a %localappdata% variable on your system, I will try to find reasons for that.
Also, which version of Windows are you using, and are there more users on your system?

**Comment by DB1973** [comment]
I am on windows 11 pro. I am at a local school district, So there is other users but not logged into this machine.

**Comment by DB1973** [comment]
not sure if this will help but I ran the  'Import-Module %localappdata%' and then the app and it returned this.

PS C:\Users\dbaughman> 'Import-Module %localappdata%'
Import-Module %localappdata%
PS C:\Users\dbaughman> + %localappdata%\set-audiodg-affinity.vbs
At line:1 char:2
+ + %localappdata%\set-audiodg-affinity.vbs
+  ~
Missing expression after unary operator '+'.
At line:1 char:4
+ + %localappdata%\set-audiodg-affinity.vbs
+    ~
You must provide a value expression following the '%' operator.
At line:1 char:4
+ + %localappdata%\set-audiodg-affinity.vbs
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'localappdata%\set-audiodg-affinity.vbs' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by Gobidev** [comment]
Ok can you try to replace all occurences of `%localappdata%` in `install.bat` with `%UserProfile%` like this:
```bat
@echo off

:: If not run as admin, open prompt
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

if '%errorlevel%' NEQ '0' (
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"="
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"

:: install vbs script to %UserProfile%
echo CreateObject("Wscript.Shell").Run "PowerShell.exe ""$Process = Get-Process audiodg; $Process.ProcessorAffinity=1; $Process.PriorityClass=""""""High""""""""", 0, True > %UserProfile%\set-audiodg-affinity.vbs
:: Affinity table
::Core # = Value = BitMask
::Core 1 = 1 = 00000001
::Core 2 = 2 = 00000010
::Core 3 = 4 = 00000100
::Core 4 = 8 = 00001000
::Core 5 = 16 = 00010000
::Core 6 = 32 = 00100000
::Core 7 = 64 = 01000000
::Core 8 = 128 = 10000000

:: remove old version of program if present
cd C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\
del set-audiodg-affinity.bat 2>NUL

:: add task scheduler job
schtasks /create /sc ONLOGON /tn audiodg-affinity /tr %UserProfile%\set-audiodg-affinity.vbs /rl HIGHEST

:: Uninstall with
:: schtasks /delete /f /tn audiodg-affinity

echo.
echo.
echo INSTALLATION FINISHED
echo.
pause
```
and run it again.
Edit: When it asks to replace the task, say yes.

**Comment by DB1973** [comment]
this is what it returned 


PS C:\Users\dbaughman> @echo off
At line:1 char:7
+ @echo off
+       ~~~
Unexpected token 'off' in expression or statement.
At line:1 char:1
+ @echo off
+ ~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@echo' can be used only as an
argument to a command. To reference variables in an expression use '$echo'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> :: If not run as admin, open prompt
:: : The term '::' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :: If not run as admin, open prompt
+ ~~
    + CategoryInfo          : ObjectNotFound: (:::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> >nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
> : The term '>' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ >nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\co ...
+ ~
    + CategoryInfo          : ObjectNotFound: (>:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> if '%errorlevel%' NEQ '0' (
>>     goto UACPrompt
>> ) else ( goto gotAdmin )
At line:1 char:3
+ if '%errorlevel%' NEQ '0' (
+   ~
Missing '(' after 'if' in if statement.
At line:1 char:19
+ if '%errorlevel%' NEQ '0' (
+                   ~~~
Unexpected token 'NEQ' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> :UACPrompt
:UACPrompt : The term ':UACPrompt' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :UACPrompt
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:UACPrompt:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman>     echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
At line:1 char:53
+     echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\geta ...
+                                                     ~
Unexpected token '^' in expression or statement.
At line:1 char:53
+     echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\geta ...
+                                                     ~
Missing closing ')' in expression.
At line:1 char:54
+     echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\geta ...
+                                                      ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Users\dbaughman>     set params = %*:"="
Set-Variable : A positional parameter cannot be found that accepts argument '%*:='.
At line:1 char:5
+     set params = %*:"="
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Variable], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetVariableCommand

PS C:\Users\dbaughman>     echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"
out-file : Could not find a part of the path 'C:\Users\dbaughman\%temp%\getadmin.vbs'.
At line:1 char:5
+     echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

PS C:\Users\dbaughman>
PS C:\Users\dbaughman>     "%temp%\getadmin.vbs"
%temp%\getadmin.vbs
PS C:\Users\dbaughman>     del "%temp%\getadmin.vbs"
del : Cannot find path 'C:\Users\dbaughman\%temp%\getadmin.vbs' because it does not exist.
At line:1 char:5
+     del "%temp%\getadmin.vbs"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\dbaughman\%temp%\getadmin.vbs:String) [Remove-Item], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

PS C:\Users\dbaughman>     exit /B
/B : The term '/B' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:10
+     exit /B
+          ~~
    + CategoryInfo          : ObjectNotFound: (/B:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> :gotAdmin
:gotAdmin : The term ':gotAdmin' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :gotAdmin
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:gotAdmin:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman>     pushd "%CD%"
pushd : Cannot find path 'C:\Users\dbaughman\%CD%' because it does not exist.
At line:1 char:5
+     pushd "%CD%"
+     ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\dbaughman\%CD%:String) [Push-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.PushLocationCommand

PS C:\Users\dbaughman>     CD /D "%~dp0"
Set-Location : A positional parameter cannot be found that accepts argument '%~dp0'.
At line:1 char:5
+     CD /D "%~dp0"
+     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> :: install vbs script to %UserProfile%
:: : The term '::' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :: install vbs script to %UserProfile%
+ ~~
    + CategoryInfo          : ObjectNotFound: (:::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> echo CreateObject("Wscript.Shell").Run "PowerShell.exe ""$Process = Get-Process audiodg; $Process.ProcessorAffinity=1; $Process.PriorityClass=""""""High""""""""", 0, True > %UserProfile%\set-audiodg-affinity.vbs
out-file : Could not find a part of the path 'C:\Users\dbaughman\%UserProfile%\set-audiodg-affinity.vbs'.
At line:1 char:1
+ echo CreateObject("Wscript.Shell").Run "PowerShell.exe ""$Process = G ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

PS C:\Users\dbaughman> :: Affinity table
:: : The term '::' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :: Affinity table
+ ~~
    + CategoryInfo          : ObjectNotFound: (:::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core # = Value = BitMask
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core # = Value = BitMask
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 1 = 1 = 00000001
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 1 = 1 = 00000001
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 2 = 2 = 00000010
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 2 = 2 = 00000010
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 3 = 4 = 00000100
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 3 = 4 = 00000100
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 4 = 8 = 00001000
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 4 = 8 = 00001000
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 5 = 16 = 00010000
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 5 = 16 = 00010000
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 6 = 32 = 00100000
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 6 = 32 = 00100000
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 7 = 64 = 01000000
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 7 = 64 = 01000000
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> ::Core 8 = 128 = 10000000
::Core : The term '::Core' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ::Core 8 = 128 = 10000000
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (::Core:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> :: remove old version of program if present
:: : The term '::' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :: remove old version of program if present
+ ~~
    + CategoryInfo          : ObjectNotFound: (:::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> cd C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\
Set-Location : A positional parameter cannot be found that accepts argument 'Menu\Programs\Startup\'.
At line:1 char:1
+ cd C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\dbaughman> del set-audiodg-affinity.bat 2>NUL
out-file : FileStream was asked to open a device that was not a file. For support for devices like 'com1:' or 'lpt1:',
call CreateFile, then use the FileStream constructors that take an OS handle as an IntPtr.
At line:1 char:1
+ del set-audiodg-affinity.bat 2>NUL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], NotSupportedException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> :: add task scheduler job
:: : The term '::' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :: add task scheduler job
+ ~~
    + CategoryInfo          : ObjectNotFound: (:::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> schtasks /create /sc ONLOGON /tn audiodg-affinity /tr %UserProfile%\set-audiodg-affinity.vbs /rl HIGHEST
WARNING: The task name "audiodg-affinity" already exists. Do you want to replace it (Y/N)? y
SUCCESS: The scheduled task "audiodg-affinity" has successfully been created.
PS C:\Users\dbaughman>
PS C:\Users\dbaughman> :: Uninstall with
:: : The term '::' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :: Uninstall with
+ ~~
    + CategoryInfo          : ObjectNotFound: (:::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> :: schtasks /delete /f /tn audiodg-affinity
:: : The term '::' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ :: schtasks /delete /f /tn audiodg-affinity
+ ~~
    + CategoryInfo          : ObjectNotFound: (:::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman>
PS C:\Users\dbaughman> echo.
echo. : The term 'echo.' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ echo.
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (echo.:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> echo.
echo. : The term 'echo.' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ echo.
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (echo.:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\dbaughman> echo INSTALLATION FINISHED
INSTALLATION
FINISHED
PS C:\Users\dbaughman> echo.
echo. : The term 'echo.' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ echo.
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (echo.:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Gobidev** [comment]
Try to paste the content in a `install.bat` file and run that by double clicking it, not directly in a command prompt

**Comment by Gobidev** [comment]
You can download the modified version of the script here:
https://raw.githubusercontent.com/Gobidev/voicemeeter-auto-affinity/2294d61a695bd06c053e7d82516719137df28bf7/install.bat

Just right click and click "Save as.." and make sure it does not have a .txt file extension (remove it, if it is added by your browser).
When you have this new `install.bat` file, try if that one works.

**Comment by DB1973** [comment]
That fixed it!

Thanks for all your help.

**Comment by Gobidev** [comment]
No problem :) I will release the updated version as v2.1
