### ISSUE TITLE
VBS script not working on some Windows installations

### ISSUE THREAD

**Issue by SuperiorWes** [Gobidev/voicemeeter-auto-affinity#2]
I run it. CMD pops up asking Y/N, I put Y then enter. 
Seems all good. Next time i run my PC, nothing happens. Affinity isn't changed.

**Comment by Gobidev** [comment]
Are you using v2.1 or v2 of the script?
If you are on v2, try v2.1, that fixed an issue someone else was having.
If it still does not work, please provide the entire output v2.1 produces when you run it.

**Comment by SuperiorWes** [comment]
Yes, i just tried it again. I run it, it says that one already exists to I overwrite it. I then proceed to restart pc and it doesn't change the affinity.

WARNING: The task name "audiodg-affinity" already exists. Do you want to replace it (Y/N)? y
SUCCESS: The scheduled task "audiodg-affinity" has successfully been created.


INSTALLATION FINISHED

Press any key to continue . . .

**Comment by SIGSEGV-0x01** [comment]
I had the same issue with v2.1.

Running install.bat indicates success and "audiodg-affinity" appears in the Task Scheduler. "set-audiodg-affinity.vbs" has been created under %UserProfile%. Running "set-audiodg-affinity.vbs" returns no result and does not change the affinity. Opening CMD as administrator and running "set-audiodg-affinity.vbs" with Wscript will change the affinity.

I hope this gives you some context.

**Comment by Gobidev** [comment]
@SuperiorWes @SIGSEGV-0x01 can you launch the program `Task Scheduler` and under "Active Tasks", double click "audiodg-affinity".
![Screenshot_task_scheduler](https://user-images.githubusercontent.com/50576978/216687348-51649c8a-8cc5-4409-bb7a-e56638cba14c.png)
Then check if the box "Run with highest priviliges" is checked (like in the screenshot) and if under actions the path to the vbs script is set correctly.

**Comment by SuperiorWes** [comment]
@Gobidev That was already enabled. I checked when getting on PC today and the affinity was not set. Heres what I see https://i.imgur.com/4ytjDHx.gif

**Comment by Gobidev** [comment]
It looks like everything is configured correctly, very strange that it is not working. You might have to go back to [v1.1](https://github.com/Gobidev/voicemeeter-auto-affinity/releases/tag/v1.1) again if that worked fine for you and accept the admin prompt at every login. Sorry, but I have no idea what could cause this, probably just Windows being weird.

**Comment by SuperiorWes** [comment]
Luckily i dont really have the affinity issue. Its more or less for other people. I'll let you know if this doesn't work for others

**Comment by SIGSEGV-0x01** [comment]
@Gobidev Yes, everything seems to be configured correctly. I'll revert back to v1.1 for now. Thanks for keeping this script updated.

**Comment by SIGSEGV-0x01** [comment]
@Gobidev @SuperiorWes 
After some testing, I found that signing out the user account and signing back in again changes the affinity. Also, audiodg.exe starts with slight delay when Windows boots up on my setup. Therefore, my current workaround is to add an additional trigger policy to the audiodg-affinity task that triggers the script at startup with a 30 second delay. Hope this helps.

**Comment by Gobidev** [comment]
@SIGSEGV-0x01 thank you, that is probably the issue! I made [an updated version](https://raw.githubusercontent.com/Gobidev/voicemeeter-auto-affinity/5243d6fb0e070a2edc7f007b29acbcae2a821e9b/install.bat) that adds a 20 second delay to the logon trigger (to download, right click -> save as, make sure to remove the .txt extension). @SuperiorWes can you also test if this works for you? If it does, I will release it as v2.2.

**Comment by SuperiorWes** [comment]
This worked, perfect!
