### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by froi80** [Gobidev/voicemeeter-auto-affinity#6]
After installing, I tried to run set-audiodg-affinity.vbs to see if it's going to work. but it didn't 
![image](https://github.com/Gobidev/voicemeeter-auto-affinity/assets/49754964/3c7e9dbf-5281-4223-9804-fd8508b9e943)

**Comment by Gobidev** [comment]
The script needs to be run as administrator, which is done when it is executed by the Task Scheduler. Manually running it without these permissions won't do anything.
