### ISSUE TITLE
This made crackling worse for me

### ISSUE THREAD

**Issue by ShayBox** [Gobidev/voicemeeter-auto-affinity#7]
This seems to set the affinity to only core 0 but that's an SMT/HT thread for me, and I need more than one core selected as my 1950x doesn't have very high single-core performance. Using process lasso with Disable SMT and manually disabling the last 8 cores on the secondary cpu package and setting process priority to high solved it for me.

**Comment by Gobidev** [comment]
In this case, the `Process.ProcessorAffinity=1` in the install file can be set manually according to the [CPU Table Examples](https://github.com/Gobidev/voicemeeter-auto-affinity/tree/main/CPU%20Table%20Examples).
